export const data = [{
        _id: 1,
        name: "Cothing Set",
        price: 1200,
        image: "/img/sliders/clothing-set.jpeg",
        category: "Clothing",
    },
    {
        _id: 2,
        name: "Hats",
        price: 500,
        image: "/img/sliders/hats.jpg",
        category: "Clothing",
    },
    {
        _id: 3,
        name: "Jeans",
        price: 500,
        image: "/img/sliders/jeans.jpeg",
        category: "Clothing",
    },
    {
        _id: 4,
        name: "Shoes",
        price: 900,
        image: "/img/sliders/shoes.jpeg",
        category: "Clothing",
    },
    {
        _id: 5,
        name: "Sweaters",
        price: 900,
        image: "/img/sliders/sweaters.jpeg",
        category: "Clothing",
    },
    {
        _id: 6,
        name: "Tie",
        price: 500,
        image: "/img/sliders/tie.jpg",
        category: "Clothing",
    },
    {
        _id: 7,
        name: "Camera",
        price: 35000,
        image: "/img/sliders/camera.jpg",
        category: "Electronics",
    },
    {
        _id: 8,
        name: "Earbuds",
        price: 30000,
        image: "/img/sliders/earbuds.jpeg",
        category: "Electronics",
    },
    {
        _id: 9,
        name: "Headphones",
        price: 1500,
        image: "/img/sliders/headphones.jpeg",
        category: "Electronics",
    },
    {
        _id: 10,
        name: "Iphone",
        price: 90000,
        image: "/img/sliders/iphone.jpeg",
        category: "Electronics",
    },
    {
        _id: 11,
        name: "IWatch",
        price: 30000,
        image: "/img/sliders/iwatch.jpeg",
        category: "Electronics",
    },
    {
        _id: 12,
        name: "TV",
        price: 10000,
        image: "/img/sliders/tv.jpeg",
        category: "Electronics",
    },
    {
        _id: 13,
        name: "TV",
        price: 10000,
        image: "/img/sliders/tv.jpeg",
        category: "Sports",
    },
];

export const cities = [{
        image: "/img/delhi.png",
        title: "Delhi",
        key: 1,
    },
    {
        image: "/img/bangalore.png",
        title: "Bangalore",
        key: 2,
    },
    {
        image: "/img/chennai.png",
        title: "Chennai",
        key: 3,
    },
    {
        image: "/img/hyderabad.png",
        title: "Hyderabad",
        key: 4,
    },
];